# Generated by Django 5.0.7 on 2024-07-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_winner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='winner_id',
            new_name='winner',
        ),
    ]
