# Generated by Django 5.0.7 on 2024-07-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
